### ISSUE TITLE
HucaresReact: Tables initially don't have page number selected

### ISSUE THREAD

**Issue by DonatasTamosauskas** [HuCaresTeam/hucares#83]
When MLP/DLP/Cameras tab is opened for the first time no page number is selected.
If arrow to move to the next or previous page is clicked, all records from the tables disappear.

**Comment by DonatasTamosauskas** [comment]
@SSMellow Maybe you know how to fix this?

**Comment by SSMellow** [comment]
Saw that problem. Maybe we should set page on componentDidMount. I’ll do some research

**Comment by SSMellow** [comment]
Fixed
